# Generated by Django 5.2.3 on 2025-08-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=50)),
                ('align', models.CharField(max_length=10)),
                ('image', models.URLField()),
                ('link', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
